### ISSUE TITLE
Incompatibility with Starlight

### ISSUE THREAD

**Issue by magneticflux-** [BasiqueEvangelist/FlashFreeze#5]
```
[15:22:02] [Server thread/ERROR]: Exception stopping the server
java.util.concurrent.CompletionException: java.lang.ClassCastException: class me.basiqueevangelist.flashfreeze.UnknownBlockState cannot be cast to class net.minecraft.class_2680 (me.basiqueevangelist.flashfreeze.UnknownBlockState and net.minecraft.class_2680 are in unnamed module of loader org.quiltmc.loader.impl.launch.knot.KnotClassLoader @4f6f416f)
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.2) ~[?:?]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
	at ca.spottedleaf.starlight.common.light.StarLightInterface.propagateChanges(StarLightInterface.java:529) ~[starlight-1.1.1+fabric.ae22326.jar:?]
	at net.minecraft.world.chunk.light.LightingProvider.doLightUpdates(LightingProvider:1108) ~[?:?]
	at net.minecraft.server.world.ServerLightingProvider.runTasks(ServerLightingProvider:188) ~[?:?]
	at net.minecraft.server.world.ServerLightingProvider.method_19505(ServerLightingProvider:167) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.runNext(TaskExecutor:91) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.runWhile(TaskExecutor:146) ~[?:?]
	at net.minecraft.util.thread.TaskExecutor.run(TaskExecutor:102) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) [?:?]
Caused by: java.lang.ClassCastException: class me.basiqueevangelist.flashfreeze.UnknownBlockState cannot be cast to class net.minecraft.class_2680 (me.basiqueevangelist.flashfreeze.UnknownBlockState and net.minecraft.class_2680 are in unnamed module of loader org.quiltmc.loader.impl.launch.knot.KnotClassLoader @4f6f416f)
	at ca.spottedleaf.starlight.common.light.StarLightEngine.getBlockState(StarLightEngine.java:298) ~[starlight-1.1.1+fabric.ae22326.jar:?]
	at ca.spottedleaf.starlight.common.light.StarLightEngine.performLightIncrease(StarLightEngine.java:1149) ~[starlight-1.1.1+fabric.ae22326.jar:?]
	at ca.spottedleaf.starlight.common.light.SkyStarLightEngine.lightChunk(SkyStarLightEngine.java:554) ~[starlight-1.1.1+fabric.ae22326.jar:?]
	at ca.spottedleaf.starlight.common.light.StarLightEngine.light(StarLightEngine.java:907) ~[starlight-1.1.1+fabric.ae22326.jar:?]
	at ca.spottedleaf.starlight.common.light.StarLightInterface.lightChunk(StarLightInterface.java:427) ~[starlight-1.1.1+fabric.ae22326.jar:?]
	at net.minecraft.server.world.ServerLightingProvider.mdb630aa$lambda$lightChunk$6$2(ServerLightingProvider:697) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	... 10 more
```

**Comment by BasiqueEvangelist** [comment]
Thanks for the report! I may have wrapped the incorrect method :sweat_smile:

**Comment by BasiqueEvangelist** [comment]
Could you try the GH Actions build for 10e06b1c8ed60aa04cd04527db0b71d83bd93df7? It should fix the issue

**Comment by magneticflux-** [comment]
Now it prints different errors:
```
[16:19:38] [minecraft_overworld - Light/ERROR]: Failed to light chunk [-99, -374]
java.util.concurrent.CompletionException: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: minecraft:DUMMY
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.2) ~[?:?]
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.redirect$zhm000$redirectExecuteTask(ThreadExecutor:521) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
	at net.minecraft.server.world.ServerChunkManager$MainThreadExecutor.runTask(ServerChunkManager:566) ~[?:?]
	at net.minecraft.server.world.ServerChunkManager.executeQueuedTasks(ServerChunkManager:279) ~[?:?]
	at net.minecraft.server.MinecraftServer.runOneTask(MinecraftServer:13778) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runTask(MinecraftServer:752) ~[client-intermediary.jar:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:116) ~[?:?]
	at net.minecraft.server.MinecraftServer.runTasksTillTickEnd(MinecraftServer:736) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$dkk000$modifiedRunLoop(MinecraftServer:7389) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer:644) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer:258) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:1589) [?:?]
Caused by: net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: minecraft:DUMMY
	at net.minecraft.util.Identifier.<init>(Identifier:41) ~[?:?]
	at net.minecraft.util.Identifier.<init>(Identifier:46) ~[?:?]
	at net.minecraft.world.ChunkSerializer.redirect$zim000$dontLoadIfUnknown(ChunkSerializer:619) ~[?:?]
	at net.minecraft.world.ChunkSerializer.method_39797(ChunkSerializer:422) ~[?:?]
	at net.minecraft.world.chunk.WorldChunk.loadEntities(WorldChunk:434) ~[?:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17227(ThreadedAnvilChunkStorage:744) ~[?:?]
	at com.mojang.datafixers.util.Either.lambda$mapLeft$0(Either.java:162) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.util.Either.mapLeft(Either.java:162) ~[datafixerupper-5.0.28.jar:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_20460(ThreadedAnvilChunkStorage:732) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) ~[?:?]
	... 13 more
```
https://crashy.net/HceU2522LTSKGbgJJkm6

**Comment by BasiqueEvangelist** [comment]
WHY DO THESE BUGS NOT APPEAR WHENEVER I TEST IT AAAAAAAA

**Comment by BasiqueEvangelist** [comment]
I've tried to fix this in 8fe647fa6a18ecca9efa53bbaeb6acdf45e9c08d

**Comment by magneticflux-** [comment]
It looks like it's working now!

![2022-08-07_16 39 00](https://user-images.githubusercontent.com/9124288/183312123-6dc9fabe-59b3-4850-865f-5ca64a6af8b3.png)

**Comment by BasiqueEvangelist** [comment]
Thank you for testing FF and reporting these issues! :heart:
I'll make a full release tomorrow
